version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres_user:pw_library@db:5432/library_db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: pw_library
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"  # Используем стандартный порт 5432
